### ISSUE TITLE
Should deleted alts be mentioned?

### ISSUE THREAD

**Issue by spotlightishere** [MikeModder/Kyle-Alt-List#8]
Some alts have thankfully been deleted, such as Woodstock. Should these be listed for reference?

**Comment by MikeModder** [comment]
I'd say no. If you'd like to make another file for deleted ones you can. I say this because this list is meant to be (at least slightly) copy/paste hackban friendly and including deleted alts would only take up more space.

**Comment by spotlightishere** [comment]
Nah, that's good. Thanks for clarifying.
